name: css_mobile
description: CSS (Customer Self Service) merupakan one stop aplikasi untuk memenuhi kebutuhan customer terbaik JNE. Dengan power apps CSS, kamu akan mendapatkan pengalaman luar biasa dalam berkirim paket. Bisa mendapatkan fasilitas Poin, Diskon, Pickup, Monitoring, COD, hingga Cashless didalam satu genggaman. Cukup dengan 10 menit langsung bisa dipakai dan siap menjadi partner bisnis online kamu.
publish_to: 'none'

version: 1.0.69+70

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.4.2+1
  form_validator: ^2.1.1
  flutter_flavor: ^3.1.1
  device_info_plus: ^9.1.1
  flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  flutter_svg: ^1.1.6
  dropdown_search: ^5.0.6
  lottie: ^2.7.0
  package_info_plus: ^8.0.0
  geocoding: ^3.0.0
  geolocator: ^10.1.0
  marquee: ^2.2.3
  pinput: ^3.0.1
  connectivity_plus: ^5.0.2
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.1
  flutter_barcode_scanner: ^2.0.0
  google_maps_flutter: ^2.6.1
  collection: ^1.18.0
  barcode: ^2.2.6
  barcode_widget: ^2.0.4
  pdf: ^3.10.8
  screenshot: ^3.0.0
  printing: ^5.12.0
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.3
  image_picker: ^1.1.1
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^6.2.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  webview_flutter: ^4.8.0
  infinite_scroll_pagination: ^4.0.0
  bubble: ^1.2.1
  share_plus: ^10.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  flutter_hooks: ^0.20.5
  logger: ^1.3.0
  firebase_crashlytics: ^4.1.5
  file_picker: ^5.2.0
  firebase_core: ^3.8.0
  fl_chart: ^0.36.0
  photo_view: ^0.14.0

dependency_overrides:
  fading_edge_scrollview: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

lint_staged:
  'lib/**.dart': dart format && dart fix --apply && dart analyze --fatal-infos --fatal-warnings