// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class CssFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLomk0vDOiCzfZhh2dy00ZjQGErVuZFtY',
    appId: '1:558047279467:web:f4e62f4fa403a863b6b42e',
    messagingSenderId: '558047279467',
    projectId: 'css-mobile-7d974',
    authDomain: 'css-mobile-7d974.firebaseapp.com',
    storageBucket: 'css-mobile-7d974.appspot.com',
    measurementId: 'G-G4YFQCG2CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHIcGL8tTU-R6KDkigcyOi1TKdpMK4w7o',
    appId: '1:558047279467:android:fed39e77d92f4091b6b42e',
    messagingSenderId: '558047279467',
    projectId: 'css-mobile-7d974',
    storageBucket: 'css-mobile-7d974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4eGHrYdo1cbN7yhVMNVBlM2ocXBmL5ig',
    appId: '1:558047279467:ios:721b6831aa8008e5b6b42e',
    messagingSenderId: '558047279467',
    projectId: 'css-mobile-7d974',
    storageBucket: 'css-mobile-7d974.appspot.com',
    iosBundleId: 'com.jne.css.cssMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4eGHrYdo1cbN7yhVMNVBlM2ocXBmL5ig',
    appId: '1:558047279467:ios:721b6831aa8008e5b6b42e',
    messagingSenderId: '558047279467',
    projectId: 'css-mobile-7d974',
    storageBucket: 'css-mobile-7d974.appspot.com',
    iosBundleId: 'com.jne.css.cssMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLomk0vDOiCzfZhh2dy00ZjQGErVuZFtY',
    appId: '1:558047279467:web:ae32c64e3212f23fb6b42e',
    messagingSenderId: '558047279467',
    projectId: 'css-mobile-7d974',
    authDomain: 'css-mobile-7d974.firebaseapp.com',
    storageBucket: 'css-mobile-7d974.appspot.com',
    measurementId: 'G-760TGVZG7R',
  );
}
