// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class CssFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdX2c-Cqp4qDx8y6IjUWmeWPyxPJt2_C8',
    appId: '1:852897989152:web:be217390532b0b3cedf245',
    messagingSenderId: '852897989152',
    projectId: 'cssmobile-jne',
    authDomain: 'cssmobile-jne.firebaseapp.com',
    storageBucket: 'cssmobile-jne.firebasestorage.app',
    measurementId: 'G-ZG1ZKPV112',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuKcEdR9AIMLWdPVEuDfZVZvy3h8Z4e0A',
    appId: '1:852897989152:android:11b186c9e0ba170fedf245',
    messagingSenderId: '852897989152',
    projectId: 'cssmobile-jne',
    storageBucket: 'cssmobile-jne.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC9d_p45BeKn-y7ef6_ILMZHqI6yYM3Z8',
    appId: '1:852897989152:ios:91749d55b2c2e3d0edf245',
    messagingSenderId: '852897989152',
    projectId: 'cssmobile-jne',
    storageBucket: 'cssmobile-jne.firebasestorage.app',
    iosBundleId: 'com.jne.css.cssMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC9d_p45BeKn-y7ef6_ILMZHqI6yYM3Z8',
    appId: '1:852897989152:ios:91749d55b2c2e3d0edf245',
    messagingSenderId: '852897989152',
    projectId: 'cssmobile-jne',
    storageBucket: 'cssmobile-jne.firebasestorage.app',
    iosBundleId: 'com.jne.css.cssMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdX2c-Cqp4qDx8y6IjUWmeWPyxPJt2_C8',
    appId: '1:852897989152:web:4a65514978273600edf245',
    messagingSenderId: '852897989152',
    projectId: 'cssmobile-jne',
    authDomain: 'cssmobile-jne.firebaseapp.com',
    storageBucket: 'cssmobile-jne.firebasestorage.app',
    measurementId: 'G-ZL3R4SC4HT',
  );
}
