import 'dart:async';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:css_mobile/data/connection_test.dart';
import 'package:css_mobile/data/repository/aggregasi/aggregasi_repository.dart';
import 'package:css_mobile/data/repository/auth/auth_repository.dart';
import 'package:css_mobile/data/repository/bank/bank_repository.dart';
import 'package:css_mobile/data/repository/facility/facility_repository.dart';
import 'package:css_mobile/data/repository/invoice/invoice_repository.dart';
import 'package:css_mobile/data/repository/jlc/jlc_repository.dart';
import 'package:css_mobile/data/repository/lacak_kiriman/lacak_kiriman_repository.dart';
import 'package:css_mobile/data/repository/laporanku/laporanku_repository.dart';
import 'package:css_mobile/data/repository/master/master_repository.dart';
import 'package:css_mobile/data/repository/notification/notification_repository.dart';
import 'package:css_mobile/data/repository/pengaturan/pengaturan_repository.dart';
import 'package:css_mobile/data/repository/profil/profil_repository.dart';
import 'package:css_mobile/data/repository/request_pickup/request_pickup_repository.dart';
import 'package:css_mobile/data/repository/storage/storage_repository.dart';
import 'package:css_mobile/data/repository/transaction/transaction_repository.dart';
import 'package:css_mobile/data/storage_core.dart';
import 'package:get/get.dart';

abstract class BaseController extends GetxController {
  final auth = Get.find<AuthRepository>();
  final transaction = Get.find<TransactionRepository>();
  final storage = Get.find<StorageCore>();
  final connection = Get.find<ConnectionTest>();
  final profil = Get.find<ProfilRepository>();
  final trace = Get.find<LacakKirimanRepository>();
  final jlc = Get.find<JLCRepository>();
  final setting = Get.find<PengaturanRepository>();
  final facility = Get.find<FacilityRepository>();
  final bank = Get.find<BankRepository>();
  final storageRepository = Get.find<StorageRepository>();
  final aggregation = Get.find<AggregasiRepository>();
  final requestPickupRepository = Get.find<RequestPickupRepository>();
  late StreamSubscription<ConnectivityResult> connectivitySubscription;
  final notification = Get.find<NotificationRepository>();
  final laporanku = Get.find<LaporankuRepository>();
  final invoiceRepository = Get.find<InvoiceRepository>();
  final master = Get.find<MasterRepository>();
}
